### ISSUE TITLE
enhancement dump

### ISSUE THREAD

**Issue by tetchel** [tetchel/Shexter#10]
Top priority: Resolve connection to phone through internet. Removes need for config.
Second: TUI (do it @nwam)

App
- start with phone, so it's always running - Done but needs testing (appears to stop running sometimes. maybe it crashes? need to look at logs)

Client
- "successfully sent n messages to x" needs updating for -n case - Done
- remove 'connecting...' messages for regular use - Done

Installers
- If you run the installer without CD'ing first, it won't be able to find the directory with the common files

**Comment by nwam** [comment]
@tetchel I want to continue working on this, but school and applying to jobs! I'll attempt to make more time for this because it's awesome

**Comment by tetchel** [comment]
I gave it a shot last week. It is not easy 👎 I saved your work on the "noah" branch

**Comment by nwam** [comment]
Sick! I get my own branch! I finally ran into the pushbullet text maximum. I forgot that it's only 100 👎

**Comment by tetchel** [comment]
it is horrible. that is why shexter is superior

**Comment by tetchel** [comment]
I was looking at some existing IRC clients and I thought it would be really cool if the interface could be able to potentially support other messaging services. like facebook or hangouts, it would be so cool to have CLIs for those and the whole interface could be reused!

**Comment by allan2** [comment]
APIs prone to break? Used to use XMPP back in the day.
