### ISSUE TITLE
'read'ing messages does not always display messages I sent

### ISSUE THREAD

**Issue by nwam** [tetchel/Shexter#2]
For some conversations, none of my sent messages are displayed
For some conversations, some of my sent messages are displayed
For some conversations, all of my sent messages are displayed

**Comment by allan2** [comment]
Hm...
Did you try rebooting the machine?
If that doesn't work, maybe try safe mode.
If that doesn't work, you may have to boot into your Recovery DVD and factory reset.

**Comment by tetchel** [comment]
tonight i will add more debug logs, then have you run this again, then send me the logs using adb. please install adb on your laptop so you can do this

**Comment by tetchel** [comment]
hey i reworked the way that message retrieval is done and i think it will have fixed this, give it a try tomorrow
