### ISSUE TITLE
Sending SMS messages >160 chars does not work

### ISSUE THREAD

**Issue by allan2** [tetchel/Shexter#5]
Output of `print("1234567890"*16)` is 160 chars and sends successfully.

161 chars and above and no message will be sent. Shexter still displays successful message.
e.g. one line of 161 chars does not show up.
one line of 80 and one line of 81 does not show up.

Strangely, cows are partially working.
If multiple cowsays are sent, e.g. 3 cows in succession (one cow exhibited)

```
 ______________________ 
< I like Shexter! Moo! >
 ---------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

```

the message shows up in the phone's messenger client, displaying "Not sent. Tap to try again." Tapping will send the message.

**Comment by tetchel** [comment]
This is working for most messages. [New, related bug here.](https://github.com/tetchel/Shexter/issues/9)
