### ISSUE TITLE
Settings created in /opt; not user-writable

### ISSUE THREAD

**Issue by allan2** [tetchel/Shexter#6]
`settings_fullpath` is not user-writable in current state.

going to fix soon with multi-OS best practices

http://unix.stackexchange.com/questions/204856/standard-config-file-naming-pattern-and-locations

**Comment by allan2** [comment]
used `appdirs` to load platform-specific dirs. This applies to user data, logs, cache, and config.
https://pypi.python.org/pypi/appdirs

settings file is now called `shexterrc`.

on Linux, it is stored at `$XDG_CONFIG_HOME/shexterrc`, which is most likely `~/.config/shexterrc`

Awaiting feedback on if the config location is suitable on Windows

**Comment by tetchel** [comment]
Current implementation is good on windows.
