### ISSUE TITLE
Long messages (split SMS) only sends last SMS

### ISSUE THREAD

**Issue by allan2** [tetchel/Shexter#9]
e.g. SMS is 300 characters, you will only get last 140 chars

**Comment by tetchel** [comment]
this only happens with the cows. i suspect it is due to some special character (backslash) or characters that are part of the [extended charset of 7-bit gsm](https://en.wikipedia.org/wiki/GSM_03.38#GSM_7-bit_default_alphabet_and_extension_table_of_3GPP_TS_23.038_.2F_GSM_03.38)

**Comment by tetchel** [comment]
Ok I discovered that an android API exists for this after all, so I reworked the code, I think this should work now.
